### ISSUE TITLE
Language guidelines

### ISSUE THREAD

**Issue by ghost** [uwdata/d3-tutorials#6]
The University of Washington works hard to foster an inclusive and welcoming culture for everyone in the campus community. 

Unfortunately, looking over your GitHub repositories, I have identified language that can be considered offensive due to its racist origins. Specifically the branch names, but I imagine if I looked at the code itself, I would find more.

Can you let me know when you’ll be adjusting the settings to be a inclusive product/service and follow University of Washington language guidelines?

**Comment by jheer** [comment]
This repo has only a single branch: `gh-pages`. I'm not sure if there is anything specific you are requesting that be changed, as this branch name is a required name for web publishing. Feel free to respond with more specific requests as needed.
